#!/bin/bash

# Pluming script for Linux

input=$@; [ -z $input ] && exit

search()     { "$BROWSER" "https://duckduckgo.com/?q=$@"; }
youtube()    { "$BROWSER" "https://www.youtube.com/results?search_query=$@"; }
reddit()     { "$BROWSER" "https://old.reddit.com/search?q=$@&include_over_18=on&sort=relevance&t=all"; }
wikipedia()  { "$BROWSER" "https://en.wikipedia.org/wiki/$@"; }
open()       { xdg-open "$(find ~ -type f -name $@ | head -n 1)"; }
location()   { find ~ -type f -name $@ | head -n 1 | tr -d '\n' | xclip -sel clip; }

command -v qrencode >/dev/null && qrcode() { qrencode "$@" -s 10 -o /tmp/qr.png && xdg-open /tmp/qr.png; }
echo "$input" | grep "^.*\.[A-Za-z]\+.*" >/dev/null && gotourl() { "$BROWSER" "$@"; }
echo "$input" | grep "^.*@.*\.[A-Za-z]\+$" >/dev/null && email() { xdg-email "$@"; }
man -k "^$input$" >/dev/null && manual() { man -Tpdf "$input" | zathura - ;}

func="$(declare -F | awk '{print $3}' | dmenu -b -i -p "Plumb '$input':")"

[ -z "$func" ] || "$func" "$input"
